name: Deploy to Vercel
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - name: Pull Vercel project settings
        run: npx vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dOhb6312wndMeuoDrn1XJXuo
          VERCEL_PROJECT_ID: prj_nSXCUADGGQn7sFBE2STgg3qfQTU9
      - name: Build with Vercel
        run: npx vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dOhb6312wndMeuoDrn1XJXuo
          VERCEL_PROJECT_ID: prj_nSXCUADGGQn7sFBE2STgg3qfQTU9
      - name: Deploy prebuilt to Vercel
        run: npx vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: team_dOhb6312wndMeuoDrn1XJXuo
          VERCEL_PROJECT_ID: prj_nSXCUADGGQn7sFBE2STgg3qfQTU9
